# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will assemble (compile) a Java project with Gradle
# and cache/restore any dependencies to improve execution time.

name: Java Compile Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile (assemble) with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assemble
